import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.szerencsejatek.hu/');
  await page.getByRole('button', { name: 'ÖSSZES SÜTI ENGEDÉLYEZÉSE' }).click();
  await page.getByRole('link', { name: 'Belépés és Regisztráció' }).click();
  await page.getByRole('textbox', { name: 'Felhasználónév, vagy email cím' }).click();
  await page.getByRole('textbox', { name: 'Felhasználónév, vagy email cím' }).fill('attilagyori');
  await page.getByRole('textbox', { name: 'Felhasználónév, vagy email cím' }).press('Tab');
  await page.getByRole('textbox', { name: 'Jelszó' }).fill('Landmark99');
  await page.getByRole('button', { name: 'Bejelentkezés' }).click();
  await page.locator('.sas-popup__close-overlay').click();
  await page.getByText('Lottók').click();
  await page.getByRole('link', { name: 'Ötöslottó' }).click();
  await page.getByRole('link', { name: 'Hatoslottó' }).click();
  await page.getByRole('link', { name: 'Skandináv lottó' }).click();
  await page.getByRole('link', { name: 'Eurojackpot' }).click();
  await page.getByText('1', { exact: true }).nth(1).click();
  await page.getByText('25').nth(2).click();
  await page.getByText('28').nth(1).click();
  await page.getByText('48').first().click();
  await page.getByText('45').first().click();
  await page.getByText('10').nth(2).click();
  await page.getByText('11').nth(1).click();
  await page.getByRole('button', { name: '  Kosárba' }).click();
  await page.getByText('Lottók').click();
  await page.getByRole('link', { name: 'Eurojackpot' }).click();
  await page.getByText('1', { exact: true }).nth(2).click();
  await page.getByText('12345678910111213141516171819202122232425262728293031323334353637383940414243444').first().click();
  await page.getByText('33').first().click();
  await page.getByText('39').first().click();
  await page.getByText('49').first().click();
  await page.getByText('5', { exact: true }).nth(2).click();
  await page.getByText('9', { exact: true }).nth(1).click();
  await page.getByRole('button', { name: '  Kosárba' }).click();
  await page.getByText('Lottók').click();
  await page.getByRole('link', { name: 'Eurojackpot' }).click();
  await page.getByText('21').first().click();
  await page.getByText('5', { exact: true }).nth(1).click();
  await page.getByText('24').first().click();
  await page.getByText('28').nth(2).click();
  await page.getByText('34').first().click();
  await page.getByText('48').first().click();
  await page.getByText('5', { exact: true }).nth(2).click();
  await page.getByText('10').nth(2).click();
  await page.getByRole('button', { name: '  Kosárba' }).click();
  await page.getByText('Lottók').click();
  await page.getByRole('link', { name: 'Eurojackpot' }).click();
  await page.getByText('13').first().click();
  await page.getByText('12345678910111213141516171819202122232425262728293031323334353637383940414243444').first().click();
  await page.getByText('27').first().click();
  await page.getByText('21').first().click();
  await page.getByText('48').first().click();
  await page.getByText('4', { exact: true }).nth(1).click();
  await page.getByText('8', { exact: true }).nth(1).click();
  await page.getByRole('button', { name: '  Kosárba' }).click();
  await page.getByText('Lottók').click();
  await page.getByRole('link', { name: 'Eurojackpot' }).click();
  await page.getByText('31').first().click();
  await page.getByText('34').first().click();
  await page.getByText('29').first().click();
  await page.getByText('39').first().click();
  await page.getByText('46').nth(1).click();
  await page.getByText('43').nth(1).click();
  await page.getByText('5', { exact: true }).nth(2).click();
  await page.getByText('10').nth(2).click();
  await page.getByRole('button', { name: '  Kosárba' }).click();
});